version: "3.4"

services:
  binary_coffee:
    container_name: bot_telegram
    build:
      context: .
      args:
        - CHANNEL=${CHANNEL}
        - TOKEN=${TOKEN}
        - RSS_FEED=${RSS_FEED}
    restart: always
